# Generated by Django 3.1.7 on 2021-03-26 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('SCS', 'Scissor Lifts'), ('BOM', 'Boomlifts'), ('TEL', 'Telehandlers'), ('EXC', 'Excavators'), ('SKD', 'Skid Steers'), ('CMP', 'Compactors'), ('LDR', 'Loaders'), ('CRL', 'Cralwers'), ('FRK', 'Forklifts'), ('GEN', 'Generators'), ('LTR', 'Light Towers')], default='SCS', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='day_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='Default Description, this item will have info added later!', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='make',
            field=models.CharField(choices=[('CAT', 'Catarpillar'), ('DTW', 'Ditch Witch'), ('BRT', 'Baretto'), ('GEN', 'Genie'), ('CPN', 'Chicago Pneumatic'), ('HUS', 'Husqvarna'), ('HYS', 'Hyster'), ('JCB', 'JCB'), ('JDR', 'John Deere'), ('MUS', 'Mustang'), ('VER', 'Vermeer'), ('TOR', 'Toro'), ('WNU', 'Wacker Neuson'), ('YNM', 'Yanmar')], default='GEN', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='model',
            field=models.CharField(default='Default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='month_price',
            field=models.IntegerField(default=9999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='week_price',
            field=models.IntegerField(default=66),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='year',
            field=models.IntegerField(default=2020),
            preserve_default=False,
        ),
    ]
