# Generated by Django 3.1.7 on 2021-03-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210325_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_main',
            field=models.ImageField(blank=True, null=True, upload_to='\\images'),
        ),
    ]
