# Generated by Django 3.1.7 on 2021-04-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210401_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_for_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
